"""empty message

Revision ID: 73b071601fab
Revises: dcc9bad4bd25
Create Date: 2019-03-31 22:10:25.716304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b071601fab'
down_revision = 'dcc9bad4bd25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('commentnum', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'commentnum')
    # ### end Alembic commands ###
