"""empty message

Revision ID: b6711de6d117
Revises: e82e4818fece
Create Date: 2019-03-29 23:14:50.900543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6711de6d117'
down_revision = 'e82e4818fece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'time')
    # ### end Alembic commands ###
