"""empty message

Revision ID: dcc9bad4bd25
Revises: b6711de6d117
Create Date: 2019-03-31 21:09:35.046497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc9bad4bd25'
down_revision = 'b6711de6d117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('block', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'block')
    # ### end Alembic commands ###
